steps:
# Deploy Cloud Function using Node.js 18 runtime
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud beta functions deploy helloHttp \
      --runtime=nodejs18 \
      --source=. \
      --trigger-http

logsBucket: 'gs://mylogs-1'
options:
  logging: 'GCS_ONLY'