steps:
# Deploy Cloud Function using Node.js 18 runtime with unauthenticated access
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud functions deploy home \
      --runtime=nodejs18 \
      --source=. \
      --trigger-http \
      --allow-unauthenticated

logsBucket: 'gs://mylogs-1'
options:
  logging: 'GCS_ONLY'
