steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - helloHttp
  - --source=.
  - --trigger-http
  - --runtime=nodejs18

logsBucket: 'gs://mylogs-1'
options:
  logging: 'GCS_ONLY'